New heterogeneous atmosphere design
eradiate/eradiate pull request #102
Opened 2021-06-28 14:28 UTC by nollety

# Description

This pull request introduces a new heterogeneous atmosphere design. 

# Checklist

- [ ] The code follows the relevant coding guidelines
- [ ] The code generates no new warnings
- [ ] The code is appropriately documented
- [ ] The code is tested to prove its function
- [ ] The feature branch is rebased on the current state of the `main` branch
- [ ] I give permission that the Eradiate project may redistribute my contributions under the terms of its license

2021-08-11 07:55 UTC, nollety commented
@leroyvn, I'm getting a `RuntimeError: ​[PluginManager] Plugin "lut" not found!` when trying the use the lut plugin. Any idea what I'm doing wrong? I've run ninja to update the eradiate kernel.

Here is the full traceback:
```shell
_____________________________________________________________________________________________________________________________________________________ test_particle_load _____________________________________________________________________________________________________________________________________________________

mode_mono = None

    def test_particle_load(mode_mono) -> None:
        """Produces a kernel dictionary that can be loaded by the kernel."""
        ctx = KernelDictContext()
        particle_layer = ParticleLayer()
>       assert KernelDict.new(particle_layer, ctx=ctx).load() is not None

eradiate/scenes/atmosphere/tests/test_particles.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = {'type': 'scene', 'phase_atmosphere': {'type': 'lut', 'values': '277.2401,276.2332,273.3426,268.6447,262.4106,254.9236...0, 0, 500.5, 499.5],
 [0, 0, 0, 1]], 'bsdf': {'type': 'null'}, 'interior': {'type': 'ref', 'id': 'medium_atmosphere'}}}

    def load(self) -> "mitsuba.render.Scene":
        """
        Load kernel object from self.
    
        .. note:: Requires a valid selected operational mode.
    
        Returns → :class:`mitsuba.render.Scene`:
             Kernel object.
        """
        self.check()
        from mitsuba.core.xml import load_dict
    
>       return load_dict(self.data)
E       RuntimeError: ​[PluginManager] Plugin "lut" not found!

eradiate/scenes/core.py:140: RuntimeError
================================================================================================================================================== short test summary info ===================================================================================================================================================
FAILED eradiate/scenes/atmosphere/tests/test_particles.py::test_particle_load - RuntimeError: ​[PluginManager] Plugin "lut" not found!
```

2021-08-11 08:26 UTC, nollety commented
Oh, okay, it's not `"lut"` (as mentioned in the docs) but `"lutphase"`. Thanks @schunkes!

2021-08-25 09:47 UTC, leroyvn requested changes
Hi @nollety, nice PR :) My comments mostly have to do with style, nothing very critical. Once those are fixed, we can merge!

2021-08-25 09:47 UTC, leroyvn commented on eradiate/scenes/atmosphere/_heterogeneous_new.py
> +
A lot of the branching used here would not be necessary if you would have a `components` property returning all components at once. Example:
```python
@property
def components(self):
    result = [self.molecular_atmosphere] if self.molecular_atmosphere else []
    result.extend(self.particle_layers)
    return result
```

2021-08-25 09:47 UTC, leroyvn commented on eradiate/scenes/atmosphere/_heterogeneous_new.py
> +                    )
With `component` field (uses a set for optimal container lookup performance):
```python
ids = set()

for component in self.components:
    if not component.id in ids:
        ids.add(component.id)
    else:
        raise ValueError(
           f"while validating {attribute.name}: found duplicate component ID '{component.id}'; "
           f"all components (molecular atmosphere and particle layers) must have different IDs"
         )
```

2021-08-25 09:47 UTC, leroyvn commented on eradiate/scenes/atmosphere/_heterogeneous_new.py
> +            return min(bottoms)
More concise with `component` property:
```python
bottoms = [component.bottom for component in self.components]
if bottoms:
    return min(bottoms)
else:
    return 0.0 * ureg.km
```

2021-08-25 09:47 UTC, leroyvn commented on eradiate/scenes/atmosphere/_heterogeneous_new.py
> +            return max(tops)
With `component` property:
```python
tops = [component.top for component in self.components]
if bottoms:
    return max(tops)
else:
    return 10.0 * ureg.km
```

2021-08-25 09:47 UTC, leroyvn commented on eradiate/scenes/atmosphere/_heterogeneous_new.py
> +            return max(widths)
Ditto with `component` property.

2021-08-25 09:47 UTC, leroyvn commented on eradiate/scenes/atmosphere/_molecules.py
> +    has_absorption: Optional[bool] = documented(
[`Optional[X]` is equivalent to `Union[X, None]`](https://docs.python.org/3/library/typing.html#typing.Optional); you don't implement this behaviour here, so your annotation should simply be:
```suggestion
    has_absorption: bool = documented(
```

2021-08-25 09:47 UTC, leroyvn commented on eradiate/scenes/atmosphere/_molecules.py
> +    has_scattering: Optional[bool] = documented(
```suggestion
    has_scattering: bool = documented(
```

2021-08-25 09:47 UTC, leroyvn commented on eradiate/scenes/atmosphere/_molecules.py
> +    )
Side remark: I'm still thinking about how to get rid of these, and I have a design solution :)

2021-08-25 09:47 UTC, leroyvn commented on eradiate/scenes/atmosphere/tests/test_molecules.py
> +def ussa76_approx_test_absorption_data_set() -> MutableMapping[str, str]:
Same comment as yesterday about type hints in test code: it's overkill, I'd rather have them removed (at least in fixtures and test functions; for utility functions, it's okay).

2021-08-30 07:55 UTC, nollety commented on eradiate/data/absorption_spectra.py
> +_ROOT_DIR = "resources/data/spectra/absorption"
I don't remember why I needed that; I just tried using a path relative to the data directory and all tests pass. I'll undo this change.

2021-08-30 08:39 UTC, nollety commented on eradiate/scenes/atmosphere/_heterogeneous_new.py
> +        elif particle_layer.top > layer.bottom >= particle_layer.bottom:
No :)

2021-08-30 08:51 UTC, nollety commented on eradiate/scenes/atmosphere/_homogeneous.py
> +            return 10.0 / self.eval_sigma_s(spectral_ctx).min()
This `min()` call is irrelevant.

2021-08-30 08:51 UTC, nollety commented on eradiate/scenes/atmosphere/_homogeneous.py
> +            return 10.0 / self.eval_sigma_s(spectral_ctx).min()
I removed it

2021-08-30 09:17 UTC, nollety commented on eradiate/scenes/atmosphere/_heterogeneous_new.py
> +    # width of the particle layers with the width of the molecular atmosphere.
I'm not sure what you mean, I was thinking about something like that:
```python
align_components_widths: bool = documented(
        attr.ib(
            default=False,
            converter=bool,
            validator=attr.validators.instance_of(bool),
        ),
        doc="Set all components' widths to the width of the component with the largest width.",
        type="bool",
        default="False",
    )
```
What do you think?

2021-08-31 13:46 UTC, nollety commented on eradiate/scenes/atmosphere/_heterogeneous_new.py
> +    # width of the particle layers with the width of the molecular atmosphere.
As discussed irl, all components widths must be aligned and we will only accept components with `width=AUTO`

2021-08-31 15:50 UTC, leroyvn reviewed
Hi @nollety, one minor comment and we'll be good to go. When it's taken care of, we can merge.

2021-08-31 15:50 UTC, leroyvn commented on eradiate/scenes/atmosphere/_molecules.py
> +    def kernel_phase(self, ctx: Optional[KernelDictContext]) -> MutableMapping:
You can hint a parameter as `Optional` **iff** it has `None` as its default (other occurences below).

2021-08-31 15:50 UTC, leroyvn commented on eradiate/scenes/atmosphere/_molecules.py
> +        if ctx.ref:
Typically here, `ctx` is required and cannot be `Optional`.

2021-08-31 16:15 UTC, merged