Refactoring of rad_profile module
eradiate/eradiate pull request #112
Opened 2021-08-13 16:01 UTC by nollety

# Description

*Describe your feature. What does it do? How does it work? If applicable mention an issue on the issue tracker*

# Checklist

- [ ] The code follows the relevant coding guidelines
- [ ] The code generates no new warnings
- [ ] The code is appropriately documented
- [ ] The code is tested to prove its function
- [ ] The feature branch is rebased on the current state of the `main` branch
- [ ] I give permission that the Eradiate project may redistribute my contributions under the terms of its license

2021-08-16 12:01 UTC, leroyvn requested changes
Hi @nollety, thanks for this PR :) It's fine overall but I'd like to switch from a constructor-based to a converter-based approach for the `from_thermoprops_params()` method.

2021-08-23 09:15 UTC, nollety commented on eradiate/radprops/rad_profile.py
> +            albedo = np.where(sigma_t != 0.0, sigma_s / sigma_t, 0.0)  # broadcast 0.0
Yes, I ignore the divide-by-zero warnings. Somehow, the warnings are still there even if I use `np.where`...

2021-08-23 09:22 UTC, nollety commented on eradiate/radprops/rad_profile.py
> +    def from_thermoprops_params(
Oh yes, I like the converter idea much better!
I did not think about using a converter. I'll refactor `US76ApproxRadProfile` and `AFGL1986RadProfile` classes to use such converters.

These are the only two classes that have a `_thermoprops` attribute, by the way. The interface (`RadProfile`) does not define a `_thermoprops` attribute or `thermoprops` property like `US76ApproxRadProfile` and `AFGL1986RadProfile` do. Or did I misunderstand your last comment?

2021-08-23 09:40 UTC, nollety commented
I'm waiting for your approval to resolve the two conversations above @leroyvn :)
I'll mark this pull request as draft until #111 is merged at which point I'll come back to rebase/refactor and squash

2021-08-23 12:15 UTC, nollety commented on eradiate/radprops/rad_profile.py
> +            albedo = np.where(sigma_t != 0.0, sigma_s / sigma_t, 0.0)  # broadcast 0.0
np.divide(sigma_s, sigma_t, where=sigma_t!= 0.0, out=np.zeros_like(sigma_s))

2021-08-24 08:44 UTC, nollety commented
@leroyvn I've squashed the commits and rebased onto the latest main; this is ready for review/merge !
I've marked the conversations above as resolved, I hope this is fine with you :)

2021-08-24 09:35 UTC, leroyvn commented
Merging, thanks @nollety!

2021-08-24 09:35 UTC, merged