Rami4atm experiment
eradiate/eradiate pull request #133
Opened 2021-10-11 15:41 UTC by schunkes

# Description

This PR adds the RAMI4ATM experiment and a specialized surface based on the `blendbsdf` mitsuba plugin.

Once the first round of feedback is done I will add more elaborate tests that compare the Rami4ATMExperiment's edge cases to the OneeDimExperiment and RamiExperiment classes.

# Checklist

- [x] The code follows the relevant coding guidelines
- [x] The code generates no new warnings
- [x] The code is appropriately documented
- [x] The code is tested to prove its function
- [x] The feature branch is rebased on the current state of the `main` branch
- [x] I give permission that the Eradiate project may redistribute my contributions under the terms of its license

2021-10-12 09:54 UTC, leroyvn commented on eradiate/experiments/_rami4atm.py
> +            result["title"] = "Top-of-canopy simulation results"
```suggestion
            result["title"] = "Top-of-atmosphere simulation results"
```

2021-10-12 09:55 UTC, leroyvn commented on eradiate/experiments/_rami4atm.py
> +        supported_mode(ModeFlags.ANY_MONO)
```suggestion
```

2021-10-12 15:11 UTC, schunkes commented
Alright, here we go again. The docstring for the CentralPatchSurface might be a bit too short, but I wasn't sure how to describe it properly.

2021-10-13 08:27 UTC, leroyvn requested changes
Hi @schunkes, we're almost there. Just a couple of small changes and we'll be good to go!

2021-10-13 08:27 UTC, leroyvn commented on eradiate/contexts.py
> +        type="quantity, optional",
```suggestion
        type="quantity or None",
```

2021-10-13 08:27 UTC, leroyvn commented on eradiate/experiments/_rami4atm.py
> +    * if no canopy is defined, the target will be set to [0, 0, 0].
Doesn't this need an update?

2021-10-13 08:27 UTC, leroyvn commented on eradiate/scenes/surface/_centralpatch.py
> +        type="float or AUTO, optional",
```suggestion
        type="float or AUTO",
        init_type="float or AUTO, optional",
```

2021-10-13 08:27 UTC, leroyvn commented on eradiate/scenes/surface/_centralpatch.py
> +        returndict = {
This should be a `KernelDict`.

2021-10-13 08:27 UTC, leroyvn commented on eradiate/scenes/surface/_centralpatch.py
> +    This class creates a square surface to which two BSDFs will be attached.
That's a bit too vague, would you mind elaborating a bit?

2021-10-13 08:27 UTC, leroyvn commented on eradiate/scenes/surface/_centralpatch.py
> +        doc="Inner surface specification. "
```suggestion
        doc="Central patch specification. "
```

2021-10-13 08:27 UTC, leroyvn commented on eradiate/scenes/surface/_centralpatch.py
> +    outer_surface: Surface = documented(
How about `background_surface` instead, to clearly emphasise the idea of a background on which a patch is applied.

2021-10-13 08:27 UTC, leroyvn commented on eradiate/scenes/surface/_centralpatch.py
> +    patch_width: t.Union[pint.Quantity, AutoType] = documented(
The more I think about it, the more I believe that this parameter can be removed. You can just use `central_patch.width` instead. What do you think?

2021-10-14 08:48 UTC, leroyvn commented on eradiate/scenes/surface/_centralpatch.py
> +        default="float or AUTO, optional",
```suggestion
        init_type="float or AUTO, optional",
        default="AUTO",
```

2021-10-14 12:32 UTC, schunkes commented
I implemented the things we discussed yesterday. 

Additionally I added a separate commit, where I set the default ray origin to cover the entire horizontal extent of the scene and be located a small distance above either the surface, canopy or atmosphere, whichever is highest.
For that I had to allow the ray origin to be set to `TargetOriginRectangle` and I don't know if there was a reason for not allowing that, which is why I kept this as a separate commit and we can leave it out if you think it should not be used.

2021-10-15 12:35 UTC, merged