Added support to new us76_u86_4 datasets and throw away usa_mls
eradiate/eradiate pull request #14
Opened 2021-01-07 10:56 UTC by nollety

# Description

I've updated the parts of the code that deal with the absorption datasets to support the new `us76_u86_4` datasets. The main new thing is the chunked datasets. These datasets have a smaller wavenumber range, 500 cm^-1, which makes them smaller in size and faster to load. The datasets are also named according to this convention:
```python
f"{engine}-{absorber}-{w_min}_{w_max}"
```
where
- `engine` is the engine used to compute the absorption cross section. Only the value `spectra` is supported at the moment, but future values could be: `hapi`, `radis`, `kspectrum`, etc
- `absorber` is the name of the absorbing gas species or mixture. Only the value `us76_u86_4` is supported at the moment, but future values could be: `n2`, `o2`, `co2`, `ch4`, `h2o`, `us62`, etc
- `w_min` and `w_max` are the minimum and maximum wavenumber values corresponding to this dataset

Example: `spectra-us76_u86_4-4000_25711` is the absorption dataset for the absorber `us76_u86_4` computed using the `SPECTRA` engine (unfortunately this name is a bit confusing) and its wavenumber range goes from 4000 to 25711 cm^-1.

This convention covers all cases I can think of so far

Changes are:
- `data.absorption_spectra`:
  - updated list of available datasets: got rid of mentions to obsolete `usa_mls` datasets.
  - added a function `available_datasets()` that scans the folder `resources/data/spectra/absorption` and returns the available (based on what the user has downloaded) datasets corresponding to a given absorber and wavenumber value.
- `radprops.absorption.compute_sigma_a()`: the function scans the available datasets before it loads the appropriate dataset, corresponding to the current wavelength value.
- radprops.rad_profile: updated `us76_u86_4-fullrange` to `spectra-us76_u86_4-4000_25711`

# Checklist

- [ ] The code follows the relevant coding guidelines
- [ ] The code generates no new warnings
- [ ] The code is apropriately documented.
- [ ] The code is tested to prove its function
- [ ] The feature branch is rebased on the current state of the `main` branch
- [ ] I give permission that the Eradiate project may redistribute my contributions under the terms of its license

2021-01-07 19:29 UTC, leroyvn requested changes
Hi @nollety, not much to say about this, just a bit of cleanup of the data index dict. I assume that the corresponding changes to data won't show up due to them being distributed outside of the data submodule, right?

2021-01-07 19:29 UTC, leroyvn commented on eradiate/data/absorption_spectra.py
> +   * - ``spectra-us76_u86_4-``
Aren't you missing a suffix here?

2021-01-07 19:29 UTC, leroyvn commented on eradiate/data/absorption_spectra.py
> +        **{"test": "tests/absorption/us76_u86_4/*.nc"}
Please format this to reduce line width to a reasonable value and remove unnecessary dict unpackings for improved legibility.

2021-01-08 10:25 UTC, nollety commented on eradiate/data/absorption_spectra.py
> +   * - ``spectra-us76_u86_4-``
Yes, thanks for catching that!

2021-01-08 10:28 UTC, nollety commented
> Hi @nollety, not much to say about this, just a bit of cleanup of the data index dict. I assume that the corresponding changes to data won't show up due to them being distributed outside of the data submodule, right?

Hi @leroyvn, thanks for the feedback. You're right, the changes affect the datasets that are on the ftp server --- you need to download the last version of these datasets from the ftp server otherwise these changes will break the previous functionalities related to absorption calculations.

2021-01-11 11:29 UTC, merged