Sensors in the atmosphere
eradiate/eradiate pull request #160
Opened 2021-12-02 16:18 UTC by schunkes

# Description

This PR adds functionality which lets Experiment classes that support atmospheres add an external medium to the sensors, which are placed inside the atmosphere's volume.

# Checklist

- [x] The code follows the relevant coding guidelines
- [x] The code generates no new warnings
- [x] The code is appropriately documented
- [x] The code is tested to prove its function
- [x] The feature branch is rebased on the current state of the `main` branch
- [x] I give permission that the Eradiate project may redistribute my contributions under the terms of its license

2021-12-02 22:05 UTC, leroyvn requested changes
Hi @schunkes, I made a bunch of comments and suggestions for a cleaner implementation. I see overall two important issues which I tried to address:

1. The code is lengthy and hard to understand, but a bounding box abstraction will make it more compact, testable and legible.
2. This implementation relies on an instance method which, by nature, is not meant for reuse unless you subclass (not doable in our case). My suggestions address this by making the duplicate component a pure function.

2021-12-02 22:05 UTC, leroyvn commented on src/eradiate/experiments/_rami4atm.py
> +
Same comment as for the 1D module.

2021-12-03 13:10 UTC, schunkes commented on src/eradiate/experiments/_onedim.py
> +    def _is_measure_inside_atm(self, measure, ctx):
I did add a method to the Atmosphere class. I agree that this kind of method makes sense and could be useful in the future as well.

2021-12-03 13:47 UTC, leroyvn reviewed
Hi @schunkes, this looks good to me—I just had a couple of comments, small details. When this is taken care of, we can squash + merge!

2021-12-03 13:47 UTC, leroyvn commented on src/eradiate/contexts.py
> +        "are positioned inside the atmosphere volume.",
Let's also broaden the scope of this doc:
```suggestion
        doc="If relevant, a kernel medium ID to reference by other kernel components.",
```

2021-12-03 13:47 UTC, leroyvn commented on src/eradiate/experiments/_onedim.py
> +    Raises a ValueError if calld with a :class:`MultiRadiancemeterMeasure` with
```suggestion
    Raises a ValueError if called with a :class:`.MultiRadiancemeterMeasure` with
```

2021-12-03 13:47 UTC, leroyvn commented on src/eradiate/experiments/_onedim.py
> +    origins that are inside as well as outside of the atmosphere.
```suggestion
    origins both inside and outside of the atmosphere.
```

2021-12-03 13:47 UTC, leroyvn commented on src/eradiate/experiments/_onedim.py
> +            return False
Still with the idea of not evaluating twice:
```suggestion
        bbox_contains = [bbox.contains(origin) for origin in measure.origins]
        if all(bbox_contains):
            return True
        elif not any(bbox_contains):
            return False
```

2021-12-03 13:47 UTC, leroyvn commented on src/eradiate/experiments/_onedim.py
> +                "medium or all must be placed outside."
How about a briefer
```suggestion
                "Inconsistent placement of MultiRadiancemeterMeasure origins. "
                "All origins must lie either inside or outside of the atmosphere."
```

2021-12-03 17:59 UTC, leroyvn commented
I made a few more tiny updates, let's merge. Thanks @schunkes!

2021-12-03 17:59 UTC, merged