`RadProfile` line cleanup
eradiate/eradiate pull request #176
Opened 2022-02-16 16:01 UTC by nollety

# Description

Resolves eradiate/eradiate-issues#143

# Checklist

- [x] The code follows the relevant coding guidelines
- [x] The code generates no new warnings
- [x] The code is appropriately documented
- [x] The code is tested to prove its function
- [x] The feature branch is rebased on the current state of the `main` branch
- [x] I give permission that the Eradiate project may redistribute my contributions under the terms of its license

2022-03-01 19:01 UTC, nollety commented
On io, full test suite ran in 20 minutes

2022-03-02 09:35 UTC, leroyvn requested changes
Hi @nollety, thanks for this much needed cleanup pass. There are a few points to be addressed:

* You introduced a kernel submodule regression in your first commit, please fix that.
* The test workload can be optimised by reducing the number of angles and with a slightly more refined mode selection choice.
* See detailed comments for the rest.

While suggesting changes, I made a few experiments, which are committed to a branch on this repo. It notably fixes the submodule regression, you can start from it if you wish.

2022-03-02 09:35 UTC, leroyvn commented on tests/02_eradiate/02_system/test_compare_rami4atm.py
> +        "spectral_cfg": ertsc.measure.MeasureSpectralConfig.new(bin_set="10nm", bins="550")
Black pass please

2022-03-02 09:35 UTC, leroyvn commented on tests/02_eradiate/02_system/test_compare_rami4atm.py
> +        "spectral_cfg": ertsc.measure.MeasureSpectralConfig.new(bin_set="10nm", bins="550")
```suggestion
        "spectral_cfg": ertsc.measure.MeasureSpectralConfig.new(wavelengths=[550])
```

2022-03-02 09:35 UTC, leroyvn commented on tests/02_eradiate/02_system/test_compare_rami4atm.py
> +    mode_ckd_double, sza, lai, artefact_dir, ert_seed_state
Running this in CKD mode makes little sense IMO: the RAMI experiment is intended to be monochromatic.
```suggestion
    mode_mono_double, sza, lai, artefact_dir, ert_seed_state
```

2022-03-02 09:35 UTC, leroyvn commented on tests/02_eradiate/02_system/test_onedim_atmosphere.py
> +        "zeniths": np.linspace(-90, 90, 19),
```suggestion
        "zeniths": np.arange(-90, 91, 15),
```

2022-03-02 09:35 UTC, leroyvn commented on tests/02_eradiate/02_system/test_onedim_atmosphere.py
> +        "zeniths": np.linspace(-90, 90, 19),
```suggestion
        "zeniths": np.arange(-90, 91, 15),
```

2022-03-02 10:22 UTC, nollety commented
On io, full test suite now runs in ~14 minutes

2022-03-02 10:25 UTC, nollety commented
Hi @leroyvn, thanks a lot for your feedback! Apologies for the submodule regression. I'll address your remaining comment and see if I can optimise further the test run time.

2022-03-02 13:15 UTC, merged