CKD datasets update
eradiate/eradiate pull request #185
Opened 2022-03-11 14:16 UTC by nollety

# Description

Add support for all `afgl_1986-*` atmospheres.

:warning: this is an anticipated pr, the data sets are not all computed just yet

# Checklist

- [ ] The code follows the relevant coding guidelines
- [ ] The code generates no new warnings
- [ ] The code is appropriately documented
- [ ] The code is tested to prove its function
- [ ] The feature branch is rebased on the current state of the `main` branch
- [ ] I give permission that the Eradiate project may redistribute my contributions under the terms of its license

2022-03-31 09:24 UTC, leroyvn requested changes
Hi @nollety, thanks for this PR. I think it deserves a little more elaborate description: there is no way for a user coming from the change log to really understand what you did here (the linked issue is on our private issue tracker so the PR description is the only resource available to everyone). I'd also appreciate if you could mention that you did some refactoring in the process (just a line, it's enough).

Regarding the code, I have only a few minor things to add.

2022-03-31 09:24 UTC, leroyvn commented on CHANGELOG.md
> +* Added complete support for CKD simulations in AFGL 1986 reference atmospheres ({ghpr}`185`).
I suggest to rephrase this like as follows (a little more descriptive regarding your PR contents):
```suggestion
* Add support for all missing AFGL 1986 reference atmospheres in CKD mode ({ghpr}`185`).
```

2022-03-31 09:24 UTC, leroyvn commented on src/eradiate/thermoprops/afgl_1986.py
> +        )
If I'm not mistaken, this function is called only once. I don't really see the point of keeping it; instead, I'd suggest to just keep the list of valid IDs as a constant:
```suggestion
VALID_MODEL_IDS = [
    "tropical",
    "midlatitude_summer",
    "midlatitude_winter",
    "subarctic_summer",
    "subarctic_winter",
    "us_standard",
]
```
and later, explicitly write those two lines. An added benefit is that you can reuse this list later (*e.g.* in your tests).

2022-03-31 09:24 UTC, leroyvn commented on src/eradiate/thermoprops/afgl_1986.py
> +    validate_model_id(model_id)
```suggestion
    if model_id not in VALID_MODEL_IDS:
        raise ValueError(
                f"model_id should be in {VALID_MODEL_IDS} (got '{value}')"
            )
```

2022-04-01 10:14 UTC, nollety commented
Hi @leroyvn, thanks for your feedback, I applied your suggestions and I've made the pull request description more verbose.
All tests passed, this PR is ready!

2022-04-06 08:33 UTC, leroyvn commented
Good, let's merge this. Thanks @nollety !

2022-04-06 08:33 UTC, merged