Fix incorrect phase function blending in multi-component atmospheres
eradiate/eradiate pull request #197
Opened 2022-03-25 16:01 UTC by nollety

# Description

Closes eradiate/eradiate-issues#155

# Checklist

- [x] The code follows the relevant coding guidelines
- [x] The code generates no new warnings
- [x] The code is appropriately documented
- [x] The code is tested to prove its function
- [x] The feature branch is rebased on the current state of the `main` branch
- [x] I give permission that the Eradiate project may redistribute my contributions under the terms of its license
- [x] :warning: update regression test: `tests/02_eradiate/03_regression/atmospheres/test_rpv_afgl1986_continental.py::test_rpv_afgl1986_continental_brfpp`

2022-03-25 18:15 UTC, nollety commented
- [ ] update regression test: `tests/02_eradiate/03_regression/atmospheres/test_rpv_afgl1986_continental.py::test_rpv_afgl1986_continental_brfpp`

2022-03-26 08:49 UTC, leroyvn requested changes
Hi @ nollety, I think your diagnostic is correct. Hereafter are a few comments on your changes—overall, mostly style issues.

2022-03-26 08:49 UTC, leroyvn commented on src/eradiate/scenes/phase/_blend.py
> +def _convert_weights(value: npt.ArrayLike) -> npt.NDArray[np.float64]:
For consistency with the `attrs` decorator naming (rule used elsewhere in the code base; the rest is a consequence of my comment on Numpy typing):
```suggestion
def _weights_converter(value: np.typing.ArrayLike) -> np.ndarray:
```

2022-03-26 08:49 UTC, leroyvn commented on src/eradiate/scenes/phase/_blend.py
> +import numpy.typing as npt
```suggestion
```

2022-03-26 08:49 UTC, leroyvn commented on src/eradiate/scenes/phase/_blend.py
> +                values=weight[np.newaxis, np.newaxis, ...],
Let's take the opportunity to use a nicer syntax:
```suggestion
                values=np.reshape(weight, (1, 1, -1)),
```

2022-03-26 08:49 UTC, leroyvn commented on src/eradiate/scenes/phase/_blend.py
> +
Obvious given the function name.
```suggestion
```

2022-03-26 08:49 UTC, leroyvn commented on src/eradiate/scenes/phase/_blend.py
> +        weight = self.weights[1:, ...].sum(axis=0)
```suggestion
        # Summed weights of all components except the first, used to 
        # set up the kernel dictionary of the phase function
        weight = self.weights[1:, ...].sum(axis=0)
```

2022-03-26 08:49 UTC, leroyvn commented on src/eradiate/scenes/phase/_blend.py
> +            # blend phase function.
Be more concise, the code explains this already:
```suggestion
            # The phase function corresponding to remaining components
            # is built recursively
```

2022-03-26 08:49 UTC, leroyvn commented on tests/02_eradiate/01_unit/scenes/phase/test_blend.py
> +    assert phase_dict.load()
I'd like to verify the type of the created object:
```suggestion
    assert phase_dict.load() is mi.PhaseFunction
```

2022-03-26 08:49 UTC, leroyvn commented on tests/02_eradiate/01_unit/scenes/phase/test_blend.py
>      assert kernel_dict.load()
```suggestion
    assert kernel_dict.load() is mi.PhaseFunction
```

2022-03-26 08:49 UTC, leroyvn commented on tests/02_eradiate/01_unit/scenes/phase/test_blend.py
>      assert kernel_dict.load()
```suggestion
    assert kernel_dict.load() is mi.PhaseFunction
```

2022-03-26 08:49 UTC, leroyvn commented on tests/02_eradiate/01_unit/scenes/phase/test_blend.py
>      assert phase.kernel_dict(ctx).load()
```suggestion
    assert phase.kernel_dict(ctx).load() is mi.PhaseFunction
```

2022-03-26 08:49 UTC, leroyvn commented on tests/02_eradiate/01_unit/scenes/phase/test_blend.py
> +    assert phase_dict.load()
```suggestion
    assert phase_dict.load() is mi.PhaseFunction
```

2022-03-26 10:14 UTC, nollety commented
Hi @leroyvn, thanks for the feedback, I applied all your suggestions!

I'll update the failing regression test reference data set and after that, this pull request should be ready.

These assertions did not work:
```python
assert kernel_dict.load() is mi.PhaseFunction
```
so I changed them into:
```python
assert isinstance(kernel_dict.load(), mi.PhaseFunction)
```
or did you have something different in mind?

2022-03-26 14:24 UTC, nollety commented
@leroyvn I have updated the reference dataset for the failing regresion test, all test pass; the pull request is ready :smiley:

2022-03-26 17:10 UTC, nollety commented
I updated the changelog

2022-03-26 19:30 UTC, leroyvn commented
> These assertions did not work:
> 
> ```python
> assert kernel_dict.load() is mi.PhaseFunction
> ```

My mistake, I reviewed this in a hurry and you did the right thing.

2022-03-26 19:31 UTC, merged