Load SRF from custom path
eradiate/eradiate pull request #270
Opened 2022-09-30 13:30 UTC by nollety

# Description

Resolves eradiate/eradiate-issues#178

# Checklist

- [ ] The code follows the relevant coding guidelines
- [ ] The code generates no new warnings
- [ ] The code is appropriately documented
- [ ] The code is tested to prove its function
- [ ] The feature branch is rebased on the current state of the `main` branch
- [ ] I updated the change log if relevant
- [ ] I give permission that the Eradiate project may redistribute my contributions under the terms of its license

2022-10-03 11:23 UTC, nollety commented
Hi @leroyvn, I updated this pull request with respect to your comments on eradiate/eradiate-issues#178, this is ready for review :smiley:

2022-10-03 12:58 UTC, leroyvn requested changes
Hi @nollety, this is much more comprehensive and it achieves more flexible behaviour. I made a couple of suggestions to take this a step further.

I think you mistakenly committed a submodule update as well, can you please roll this back?

2022-10-03 12:58 UTC, leroyvn commented on src/eradiate/scenes/measure/_core.py
> +            ds = data.load_dataset(f"spectra/srf/{value}.nc")
This won't allow loading custom files from the data store, which IMO is useful for testing purposes. Following the logic of `SolarIrradianceSpectrum`, I suggest something a bit more flexible:

```suggestion
        ds = converters.load_dataset( 
            f"spectra/srf/{value}.nc" 
            if not str(value).endswith(".nc")  # keyword for file in data store
            else value  # path to file (local or in data store)
        )
```

2022-10-07 12:44 UTC, nollety commented on src/eradiate/scenes/measure/_core.py
> +        "from the Eradiate data store."
Confirmed

2022-10-07 12:57 UTC, nollety commented
Hi @leroyvn, I applied your suggestions and tested the new behaviour, including the following usage from the tutorial on how to filter a spectral response function data set:
```python
import eradiate
from eradiate.srf_tools import filter
from eradiate.scenes.measure import MultiDistantMeasure, MeasureSpectralConfig

aqua_modis_14 = eradiate.data.load_dataset("tutorials/spectra/srf/aqua-modis-14.nc")

filtered = filter(
    srf=aqua_modis_14,
    path="aqua-modis-14-filtered.nc",
    percentage=98.0,
    verbose=True,
    interactive=True,
    dry_run=False,
)

eradiate.set_mode("ckd")

measure = MultiDistantMeasure(
   spectral_cfg=MeasureSpectralConfig.new(
       srf="aqua-modis-14-filtered.nc",
   )
)
```

Everything is working as expected :smiley:

2022-10-07 13:02 UTC, leroyvn commented
Hi @nollety, this is nice. Just for the record: `filter()` is also a Python built-in, encouraging `from eradiate.srf_tools import filter` is probably not a great idea because those two functions have nothing to do with each other. I'm pondering on renaming `filter()` to `filter_srf()` for safety.

2022-10-07 13:04 UTC, nollety commented
Yeah, I just noticed, this is bad indeed. I agree for renaming `filter` -> `filter_srf`

2022-10-07 13:12 UTC, nollety commented
Do you mind if I create another PR for the name issue?

2022-10-25 13:05 UTC, leroyvn requested changes
Hi @nollety, I have a few minor comments about the code, not much. We've already discussed a couple of extra points offline:

* please make sure that the history on the tutorial repository is clean and linear;
* please stored render the notebook again with the appropriate font package installed.

Once this is taken care of, we'll be good to go!

2022-10-25 13:47 UTC, merged