[Feature] New benchmark test suite.
eradiate/eradiate pull request #423
Opened 2024-07-18 12:42 UTC by frettini

# Description

Adding a new benchmark test suite and infrastructure to the project that will enable continuous tracking of eradiate's performance. This will help find regressions and have a better understanding of the impact of our changes to the performance of the project. 

The benchmark infrastructure is based on the ASV package which runs statistical benchmark tests. The package allows users to test the project over a range of commits and environments, and includes a browser GUI and regression tests. The package has been integrated in the `benchmarks` directory. 

The tests written are directly taken from the existing regression tests. The tests were refactored so that both the regression tests and the benchmark test both call the same library of test cases. 

Additionally, a new click CLI was added as a thin wrapper to the ASV wrapper. While ASV defaults to using a git-ref and cloning the project to benchmark it, our CLI defaults to using the current environment for tests. This favours a manual testing approach as we release new features on branches such as main or next. 
The CLI also include an update and custom version of ASVDb that lets us archive results to an external database. This will be useful to archive results to a central ASV database.

Note that the dependencies have changed and were updated accordingly. 

# Checklist

- [x] The code follows the relevant coding guidelines
- [x] The code generates no new warnings
- [x] The code is appropriately documented
- [x] The code is tested to prove its function
- [x] The feature branch is rebased on the current state of the `next` branch
- [ ] I updated the change log if relevant
- [x] I give permission that the Eradiate project may redistribute my contributions under the terms of its license

2024-07-22 13:05 UTC, leroyvn requested changes
Hi @frettini, thanks for this PR. It's overall fine, I mostly comments on style and details.

2024-07-22 13:05 UTC, leroyvn commented on src/eradiate/test_tools/test_cases/atmospheres.py
> +from eradiate.units import unit_registry as ureg
Prefer relative imports when you are in the `eradiate` package:
```suggestion
from ...experiments import AtmosphereExperiment
from ...units import unit_registry as ureg
```

2024-07-22 13:05 UTC, leroyvn commented on src/eradiate/test_tools/test_cases/atmospheres.py
> +    )
Add ending newline

2024-07-24 11:55 UTC, frettini commented on benchmarks/benchmarks/__init__.py
> +if "ASV" in os.environ:
No, ASV sets those environment variables when it uses one of the environments it created i.e. doesn't use a specified existing environment.

2024-07-24 11:57 UTC, frettini commented on benchmarks/eradiate.toml
> +x = {missing = "ignore", scalar = "ignore", bounds = "raise"}
I don't understand the suggested change, should I completely remove line 49?

2024-07-24 13:24 UTC, frettini commented on requirements/layered.yml
> +    - "asv>=0.6.*"
I have applied the change, does it need a rerun of the dependencies update process?

2024-07-25 12:10 UTC, leroyvn approved these changes
Hi @frettini, I think we're almost good to go. After you take care of the final details, we can merge!

2024-07-25 12:10 UTC, leroyvn commented on requirements/layered.yml
> +    - "asv>0.6.*"
I made a mistake in my previous suggestion:
```suggestion
    - "asv=0.6.*"
```

2024-07-25 12:10 UTC, leroyvn commented on src/eradiate/test_tools/benchmark/asvdb.py
As we discussed, adding a header here to mention where the code comes from would be good. Something like: "This is a vendored and updated copy of the asvdb project (https://github.com/rapidsai/asvdb)."

2024-07-25 12:20 UTC, leroyvn commented on requirements/layered.yml
> +    - "asv>=0.6.*"
No yet, you've already updated the lock files and got something consistent.

2024-07-26 10:16 UTC, leroyvn commented
I forced-pushed a couple of minor updates, after a squash. I removed the lock file update from the PR, I'll regenerate locks on `next` (after I also upgrade pip lock file management to the `uv` tool).

2024-07-26 10:18 UTC, merged