[Feature] New ArrayRadProp object.
eradiate/eradiate pull request #468
Opened 2024-12-17 13:57 UTC by frettini

# Description

Hello, this PR introduces ArrayRadProp, a new RadProfile that enables the user to pass radiative properties manually. Namely, it allows to pass `sigma_s` and `sigma_a` as `DataArray`. Those values are then interpolated given a `ZGrid`. The need for such a class has come to light when working on the IPRT benchmark, in which absoprtion and scattering data are directly provided for given scenarios. This feature can thus be useful for benchmarking as well as debugging.

Of note are the functions `eval_sigma_s_mono` and and `eval_sigma_a_mono`. Please also note that I have left the `ZGrid` and `levels` properties as `NotImplementedError` as I was not able to understand how those properties were used. I would also be interested in any ways of making the check in `_helpers.py` more elegant. 

The pytest  suite was run, the new feature tested in my work for IPRT and additional tests were written. Let me know if you have any comment or feedback. Many Thanks.

# Checklist

- [x] The code follows the relevant coding guidelines
- [x] The code generates no new warnings
- [x] The code is appropriately documented
- [x] The code is tested to prove its function
- [x] The feature branch is rebased on the current state of the `next` branch
- [ ] I updated the change log if relevant
- [x] I give permission that the Eradiate project may redistribute my contributions under the terms of its license

2024-12-20 09:51 UTC, leroyvn requested changes
Hi @frettini, a couple of comments and suggestions in addition to an offline discussion. Thanks a lot!

2024-12-20 09:51 UTC, leroyvn commented on src/eradiate/radprops/_array.py
> +        "2 minimum to be correctly interpolated. ",
```suggestion
        doc="``DataArray`` of absorption coefficients. "
        "The ``DataArray`` is composed of two dimensions ``{w, z}`` representing the "
        "wavelength and altitude respectively. Note that ``w`` must be of length "
        "2 minimum to be correctly interpolated.",
```

2024-12-20 09:51 UTC, leroyvn commented on src/eradiate/radprops/_array.py
> +        "2 minimum to be correctly interpolated. ",
```suggestion
        doc="``DataArray`` of scattering coefficients. "
        "The ``DataArray`` is composed of two dimensions ``{w, z}`` representing the "
        "wavelength and altitude respectively. Note that ``w`` must be of length "
        "2 minimum to be correctly interpolated.",
```

2024-12-20 09:51 UTC, leroyvn commented on src/eradiate/radprops/_array.py
> +        type="ndarray",
I missed this previously: specifying the default and the allowed init types would be good (see also on the `AtmosphereRadProfile` side).

2024-12-20 09:51 UTC, leroyvn commented on src/eradiate/radprops/_array.py
> +        doc="Method of interpolation of the absorption and scattering coefficients. ",
```suggestion
        doc="Method of interpolation of the absorption and scattering coefficients.",
```

2024-12-20 09:51 UTC, leroyvn commented on src/eradiate/radprops/_array.py
> +        default="nearest",
Which methods do we support? I think making the allowed options explicit would prevent unpleasant mistakes. That would imply changing the type to something like `Literal["nearest", "linear"]` and the `init_type` doc field to something like `{"nearest", "linear"}`. The validator can then be `attrs.validators.in_`.

2024-12-20 09:51 UTC, leroyvn commented on src/eradiate/radprops/_array.py
> +    )
```suggestion
        init_type="dict, optional",
    )
```

2024-12-20 09:51 UTC, leroyvn commented on src/eradiate/radprops/_array.py
> +        doc="Interpolation arguments passed to xarray during interpolation. ",
```suggestion
        doc="Keyword arguments passed to :meth:`xarray.DataArray.interp` when called.",
```
Also,

2024-12-20 09:51 UTC, leroyvn commented on src/eradiate/scenes/atmosphere/_molecular.py
> +        default="None",
```suggestion
        doc="Radiative property profile. "
        "If ``thermoprops`` is not ``None``, this field is automatically "
        "overridden with an :class:`.AtmosphereRadProfile` during intialization. "
        "Note that at least one of ``thermoprops`` or ``radprops_profile`` must "
        "not be ``None``.",
        type=".RadProfile or None",
        init_type=".RadProfile or None",
        default="None",
```

2025-01-02 13:33 UTC, frettini commented on src/eradiate/radprops/_array.py
> +        default="nearest",
I have added the changes, I am also unsure when to add "optional" to the "init_type". Not all attributes with defaults have it, is there a specific rule for it?

2025-01-04 21:42 UTC, leroyvn commented on src/eradiate/radprops/_array.py
> +        default="nearest",
The rule is defined in the [Numpydoc style guide](https://numpydoc.readthedocs.io/en/latest/format.html#parameters). Arguably, we haven't always applied it very well.

2025-01-04 21:47 UTC, leroyvn commented
Thanks you @frettini, we're good to go!

2025-01-04 21:48 UTC, leroyvn approved these changes
Thank you @frettini, we're good to go!

2025-01-04 21:48 UTC, merged